//
//  LocalizedStrings.swift
//  hikingHK
//
//  Created by user on 17/11/2025.
//


import Foundation

/// Central table of localized string resources used by LanguageManager.
struct LocalizedStrings {
    static let shared = LocalizedStrings()
    
    private let strings: [AppLanguage: [String: String]] = [
        .english: englishStrings,
        .traditionalChinese: traditionalChineseStrings
    ]
    
    func getString(for key: String, language: AppLanguage) -> String {
        return strings[language]?[key] ?? strings[.english]?[key] ?? key
    }
    
    private static let englishStrings: [String: String] = [
        // Common
        "app.name": "Hiking HK",
        "ok": "OK",
        "cancel": "Cancel",
        "save": "Save",
        "delete": "Delete",
        "edit": "Edit",
        "close": "Close",
        "start": "Start",
        "stop": "Stop",
        "pause": "Pause",
        "resume": "Resume",
        "done": "Done",
        
        // Auth
        "auth.name": "Name",
        "auth.email": "Email",
        "auth.password": "Password",
        "auth.create.account": "Create your hiking account.",
        "auth.sign.in.description": "Sign in to sync your hikes, badges and plans.",
        "auth.create.account.button": "Create Account",
        "auth.sign.in": "Sign In",
        "auth.have.account": "Have an account? Sign in",
        "auth.new.hiker": "New hiker? Create account",
        "auth.preparing.storage": "Preparing secure storage…",
        "auth.quick.accounts": "Quick Accounts",
        
        // Profile
        "profile.title": "Profile",
        "profile.account": "Account",
        "profile.stats": "Statistics",
        "profile.achievements": "Achievements",
        "profile.achievements.badges": "Achievements & Badges",
        "profile.goals": "Goals",
        
        // Achievements
        "achievement.unlocked": "Unlocked",
        "achievement.total": "Total",
        "achievement.filter.all": "All",
        "achievement.badge.type.distance": "Distance",
        "achievement.badge.type.peaks": "Peaks",
        "achievement.badge.type.streak": "Streak",
        "achievement.badge.type.exploration": "Exploration",
        "achievement.unlocked.on": "Unlocked on",
        "achievement.new.unlocked": "New Achievement Unlocked!",
        "achievement.view": "View",
        "achievement.congratulations": "Congratulations! You unlocked the \"{title}\" achievement!",
        
        // Achievement Titles and Descriptions
        "achievement.distance_10km.title": "Beginner Hiker",
        "achievement.distance_10km.description": "Complete 10 km of hiking",
        "achievement.distance_50km.title": "Hiking Enthusiast",
        "achievement.distance_50km.description": "Complete 50 km of hiking",
        "achievement.distance_100km.title": "Hiking Expert",
        "achievement.distance_100km.description": "Complete 100 km of hiking",
        "achievement.distance_500km.title": "Hiking Master",
        "achievement.distance_500km.description": "Complete 500 km of hiking",
        "achievement.peak_lion_rock.title": "Lion Rock Conqueror",
        "achievement.peak_lion_rock.description": "Summit Lion Rock",
        "achievement.peak_tai_mo_shan.title": "Tai Mo Shan Conqueror",
        "achievement.peak_tai_mo_shan.description": "Summit Tai Mo Shan (Hong Kong's highest peak)",
        "achievement.peak_sunset_peak.title": "Sunset Peak Conqueror",
        "achievement.peak_sunset_peak.description": "Summit Sunset Peak (Lantau Island)",
        "achievement.peak_sharp_peak.title": "Sharp Peak Conqueror",
        "achievement.peak_sharp_peak.description": "Summit Sharp Peak",
        "achievement.peak_4_peaks.title": "Four Peaks Conqueror",
        "achievement.peak_4_peaks.description": "Summit 4 different peaks",
        "achievement.streak_1_week.title": "One Week Streak",
        "achievement.streak_1_week.description": "Hike for 7 consecutive days",
        "achievement.streak_2_weeks.title": "Two Week Streak",
        "achievement.streak_2_weeks.description": "Hike for 14 consecutive days",
        "achievement.streak_1_month.title": "Monthly Streak",
        "achievement.streak_1_month.description": "Hike for 30 consecutive days",
        "achievement.explore_3_districts.title": "Explorer",
        "achievement.explore_3_districts.description": "Explore 3 different districts",
        "achievement.explore_5_districts.title": "Adventurer",
        "achievement.explore_5_districts.description": "Explore 5 different districts",
        "achievement.explore_10_districts.title": "Exploration Master",
        "achievement.explore_10_districts.description": "Explore 10 different districts",
        
        "profile.data.services": "Data & services",
        "profile.language": "Language",
        "profile.language.description": "Choose your preferred language",
        "profile.sign.out": "Sign Out",
        "profile.sign.out.confirm": "Are you sure you want to sign out?",
        
        // Stats
        "stats.planned": "planned",
        "stats.favorites": "favorites",
        "stats.logged": "logged",
        
        // Goals
        "goal.ridge_lines": "Complete 4 Ridge Lines",
        "goal.monthly_distance": "Log 50 km this month",
        "goal.completed": "Completed",
        "goal.unit.km": "km",
        "goal.unit.lines": "lines",
        
        // Services
        "service.weather.api": "HK Weather API",
        "service.csdi.api": "CSDI Geoportal API",
        "service.gps.tracking": "GPS tracking",
        "service.offline.maps": "Offline maps",
        "service.mapbox.api": "Mapbox API",
        "service.status.connected": "Connected",
        "service.status.disconnected": "Disconnected",
        "service.status.unavailable": "Unavailable",
        "service.status.unknown": "Unknown",
        
        // Trails Data
        "profile.trails.data": "Trails Data",
        "profile.trails.total": "Total Trails",
        "profile.trails.loading": "Loading trails from API...",
        "profile.trails.refresh": "Refresh Trails",
        "trails.loading": "Loading trails...",
        
        // API Status
        "api.status.title": "API Status",
        "api.status.last.checked": "Last checked",
        "api.status.never": "Never",
        "api.status.check.connection": "Check API Connection",
        "api.status.checking": "Checking...",
        "api.status.connected": "Connected",
        "api.status.disconnected": "Disconnected",
        "api.status.not.configured": "Not Configured",
        "api.status.error": "Error",
        
        // Home
        "home.title": "Home",
        "home.quick.actions": "Quick Actions",
        "home.trail.alerts": "Trail Alerts",
        "home.offline.maps": "Offline Maps",
        "home.ar.identify": "AR Identify",
        "home.location.share": "Location Share",
        "home.start.tracking": "Start Tracking",
        "home.hike.records": "Hike Records",
        "home.recommendations": "Recommendations",
        "home.species.id": "Species ID",
        "home.journal": "Journal",
        "home.sos": "Emergency SOS",
        "home.sos.confirm": "This will open the location sharing feature where you can send an emergency SOS.",
        "home.sos.open.sharing": "Open Location Sharing",
        "home.featured.trail": "Featured Trail",
        "home.elev.gain": "Elev gain",
        "home.view.trail.plan": "View trail plan",
        "home.featured.add.to.plan.confirm": "Add to upcoming plans?",
        "home.featured.add.to.plan.message": "Do you want to add this featured trail to your upcoming plans?",
        "home.next.plans": "Next plans",
        "home.add": "Add",
        "home.no.hikes.scheduled": "No hikes scheduled",
        "home.tap.add.to.plan": "Tap Add to plan your first walk",
        "home.refresh.weather": "Refresh weather",
        "home.safety": "Safety",
        "home.sos.button": "SOS",
        "home.weather.forecast": "Weather Forecast",
        "home.best.hiking.time": "Best Hiking Time",
        
        // Weather
        "weather.location.hko": "Hong Kong Observatory",
        "weather.location.kings.park": "King's Park",
        "weather.select.location": "Select Location",
        "weather.forecast.title": "Weather Forecast",
        "weather.region": "Region",
        "weather.region.hong.kong.island": "Hong Kong Island",
        "weather.region.kowloon": "Kowloon",
        "weather.region.new.territories": "New Territories",
        "weather.region.lantau": "Lantau Island",
        "weather.forecast.best.times": "Best Hiking Times",
        "weather.forecast.7day": "7-Day Forecast",
        "weather.forecast.9day": "9-Day Forecast",
        "weather.view.9day.forecast": "View 9-Day Forecast",
        "weather.forecast.today": "Today",
        "weather.forecast.comfort.index": "Comfort Index",
        "weather.forecast.precipitation": "Rain",
        "weather.forecast.no.best.times": "No best hiking times available for the selected location.",
        "weather.forecast.good.for.hiking": "Good for hiking",
        "weather.forecast.other.days": "Other days",
        "weather.temperature": "Temperature",
        "retry": "Retry",
        "weather.humidity": "Humidity",
        "weather.uv.index": "UV Index",
        
        // Weather Conditions
        "weather.condition.sunny": "Sunny",
        "weather.condition.partly.cloudy": "Partly Cloudy",
        "weather.condition.cloudy": "Cloudy",
        "weather.condition.overcast": "Overcast",
        "weather.condition.light.rain": "Light Rain",
        "weather.condition.moderate.rain": "Moderate Rain",
        "weather.condition.heavy.rain": "Heavy Rain",
        "weather.condition.thunderstorm": "Thunderstorm",
        "weather.condition.foggy": "Foggy",
        "weather.condition.windy": "Windy",
        "weather.error.cached": "Unable to load latest weather. Showing cached data.",
        "weather.suggestion.warning": "Weather warning in force. Re-plan or carry full rain gear.",
        "weather.suggestion.extreme.uv": "Extreme UV. Start pre-dawn and bring SPF/umbrella.",
        "weather.suggestion.humid": "Humid conditions. Hydrate frequently and rest more often.",
        "weather.suggestion.stable": "Conditions look stable—great time to tackle exposed ridges.",
        "weather.suggestion.good": "Partly cloudy with light easterlies. Great time to start ridge hikes before noon heat.",
        
        // Trails
        "trails.title": "Trails",
        "trails.details": "Trail Details",
        "trails.distance": "Distance",
        "trails.duration": "Duration",
        "trails.difficulty": "Difficulty",
        "trails.district": "District",
        "trails.elevation": "Elevation",
        "trails.all.difficulties": "All difficulties",
        "trails.search.prompt": "Name or district",
        "trail.checkpoints": "Route checkpoints",
        "trail.facilities": "Facilities & services",
        "trail.highlights": "Highlights",
        "trail.transportation": "Transport tips",
        "trail.start.point": "Start Point",
        "trail.end.point": "End Point",
        "trail.supply.points": "Supply Points",
        "trail.exit.routes": "Exit Routes",
        "trail.notes": "Important Notes",
        "trail.image.unavailable": "Image unavailable",
        
        // Map
        "map.interactive": "Interactive map",
        "map.start": "Start",
        "map.you": "You",
        "map.start.location": "Start {district}",
        "map.enable.location": "Enable location",
        "map.center.on.me": "Center on me",
        "map.location.disabled": "Location disabled",
        "map.mapbox.token.required": "Set MAPBOX_ACCESS_TOKEN to view live routing overlays.",
        "map.offline.mode": "Offline",
        "map.offline.available": "Offline map available",
        "map.using.offline": "Using offline map",
        "map.distance.post": "Distance Post",
        "map.distance.post.number": "Post {number}",
        
        // Distance Posts
        "distance.posts.title": "Distance Posts",
        "distance.posts.post.number": "Post {number}",
        "distance.posts.distance.from.start": "{distance} km from start",
        "distance.posts.no.posts": "No distance posts available for this trail",
        "distance.posts.loading": "Loading distance posts...",
        
        // Checkpoints
        "checkpoint.trailhead": "Trailhead",
        "checkpoint.viewpoint": "Viewpoint",
        "checkpoint.finish": "Finish",
        "checkpoint.peak": "Peak",
        "checkpoint.start": "Start",
        "checkpoint.photo.spot": "Photo spot",
        "checkpoint.starting.point": "Starting point",
        "checkpoint.photo.stop": "Photo stop",
        "checkpoint.halfway.point": "Halfway point",
        
        // Dragon's Back Checkpoints
        "checkpoint.to.tei.wan": "To Tei Wan",
        "checkpoint.dragons.back.ridge": "Dragon's Back Ridge",
        "checkpoint.big.wave.bay": "Big Wave Bay",
        "checkpoint.ng.tung.chai": "Ng Tung Chai",
        "checkpoint.bottom.fall": "Bottom Fall",
        "checkpoint.main.fall": "Main Fall",
        
        // Facilities
        "facility.country.park.toilet": "Country park toilet",
        "facility.pavilion.shelter": "Pavilion shelter",
        "facility.visitor.center": "Visitor center",
        "facility.toilet": "Toilet",
        "facility.camping": "Camping",
        "facility.big.wave.bay.showers": "Big Wave Bay showers",
        "facility.water.kiosks": "Water kiosks",
        "facility.village.stores": "Village stores",
        "facility.taxi.stand": "Taxi stand",
        
        // Checkpoint Names (MacLehose Section 4)
        "checkpoint.kei.ling.ha": "Kei Ling Ha",
        "checkpoint.kai.kung.shan": "Kai Kung Shan",
        "checkpoint.tates.cairn": "Tate's Cairn",
        "checkpoint.high.island.reservoir": "High Island Reservoir",
        "checkpoint.sharp.peak": "Sharp Peak",
        "checkpoint.tai.long.wan": "Tai Long Wan",
        "checkpoint.route.twisk": "Route Twisk",
        "checkpoint.tai.mo.shan": "Tai Mo Shan",
        "checkpoint.lead.mine.pass": "Lead Mine Pass",
        "checkpoint.nam.shan": "Nam Shan",
        "checkpoint.pak.kung.au": "Pak Kung Au",
        "checkpoint.ngong.ping": "Ngong Ping",
        "checkpoint.the.peak": "The Peak",
        "checkpoint.pok.fu.lam.reservoir": "Pok Fu Lam Reservoir",
        "checkpoint.wan.chai.gap": "Wan Chai Gap",
        "checkpoint.wong.nai.chung.gap": "Wong Nai Chung Gap",
        "checkpoint.lion.rock.park": "Lion Rock Park",
        "checkpoint.mui.wo": "Mui Wo",
        "checkpoint.pak.tam.chung": "Pak Tam Chung",
        "checkpoint.stanley.gap": "Stanley Gap",
        "checkpoint.tai.tam": "Tai Tam",
        "checkpoint.stanley": "Stanley",
        
        // Tai Mo Shan Waterfalls Trail
        "trail.b0f98fdf-2f2f-4c19-a032-654b2c73e0b7.highlight.main.fall.35.m.drop": "Main Fall 35 m drop",
        "trail.b0f98fdf-2f2f-4c19-a032-654b2c73e0b7.highlight.shaded.bamboo.forest": "Shaded bamboo forest",
        "trail.b0f98fdf-2f2f-4c19-a032-654b2c73e0b7.highlight.stream.play.area": "Stream play area",
        "trail.b0f98fdf-2f2f-4c19-a032-654b2c73e0b7.transportation": "Bus 64K/64P to Ng Tung Chai village; return identical route.",
        
        // Units
        "unit.km": "km",
        "unit.m": "m",
        "unit.h": "h",
        
        // Trail Difficulties
        "trail.difficulty.easy": "Easy",
        "trail.difficulty.moderate": "Moderate",
        "trail.difficulty.challenging": "Challenging",
        
        // Trail Districts
        "trail.district.sai.kung": "Sai Kung",
        "trail.district.hong.kong.island": "Hong Kong Island",
        "trail.district.tsuen.wan": "Tsuen Wan",
        "trail.district.sha.tin": "Sha Tin",
        "trail.district.tai.mo.shan": "Tai Mo Shan",
        "trail.district.kowloon": "Kowloon",
        "trail.district.lantau": "Lantau",
        "trail.district.tai.po": "Tai Po",
        "trail.district.new.territories.central": "New Territories Central",
        "trail.district.new.territories.northwest": "New Territories Northwest",
        
        // Trail Names and Summaries (MacLehose Section 4)
        "trail.0c8c0a67-9b84-4d4e-8f1c-2b7b4e3eb7a0.name": "MacLehose Section 4",
        "trail.0c8c0a67-9b84-4d4e-8f1c-2b7b4e3eb7a0.summary": "Iconic ridge walk from Kei Ling Ha to Tate's Cairn with panoramic views of Port Shelter.",
        "trail.0c8c0a67-9b84-4d4e-8f1c-2b7b4e3eb7a0.transportation": "Bus 99/99R to Kei Ling Ha; return via bus/minibus from Tate's Cairn tunnel portal.",
        "trail.0c8c0a67-9b84-4d4e-8f1c-2b7b4e3eb7a0.highlight.sharp.peak.vista": "Sharp Peak vista",
        "trail.0c8c0a67-9b84-4d4e-8f1c-2b7b4e3eb7a0.highlight.ma.on.shan.country.park.geology": "Ma On Shan country park geology",
        "trail.0c8c0a67-9b84-4d4e-8f1c-2b7b4e3eb7a0.highlight.golden.hour.sunrise.spot": "Golden hour sunrise spot",
        
        // Dragon's Back
        "trail.7d62f08b-24af-4da4-95bb-818e0c1cd2b5.name": "Dragon's Back",
        "trail.7d62f08b-24af-4da4-95bb-818e0c1cd2b5.summary": "Most beloved half-day hike featuring coastal scenery overlooking Shek O, Big Wave Bay, and Tai Tam Bay.",
        "trail.7d62f08b-24af-4da4-95bb-818e0c1cd2b5.transportation": "MTR Shau Kei Wan → Bus 9 to To Tei Wan; depart via bus/minibus from Big Wave Bay.",
        "trail.7d62f08b-24af-4da4-95bb-818e0c1cd2b5.highlight.shek.o.peninsula.lookout": "Shek O Peninsula lookout",
        "trail.7d62f08b-24af-4da4-95bb-818e0c1cd2b5.highlight.paragliding.take-off.site": "Paragliding take-off site",
        "trail.7d62f08b-24af-4da4-95bb-818e0c1cd2b5.highlight.surfing.beach.finale": "Surfing beach finale",
        
        // Tai Mo Shan Waterfalls
        "trail.b0f98fdf-2f2f-4c19-a032-654b2c73e0b7.name": "Tai Mo Shan Waterfalls",
        "trail.b0f98fdf-2f2f-4c19-a032-654b2c73e0b7.summary": "Family friendly nature trail showcasing four major cascades from the Ng Tung Chai waterfall series.",
        
        // MacLehose Section 1
        "trail.a1b2c3d4-e5f6-7890-abcd-ef1234567890.name": "MacLehose Section 1",
        "trail.a1b2c3d4-e5f6-7890-abcd-ef1234567890.summary": "Easy coastal walk from Pak Tam Chung to Long Ke Wan with reservoir views.",
        
        // MacLehose Section 2
        "trail.b2c3d4e5-f6a7-8901-bcde-f23456789012.name": "MacLehose Section 2",
        "trail.b2c3d4e5-f6a7-8901-bcde-f23456789012.summary": "Scenic route from Long Ke to Pak Tam Au via Sai Wan and Ham Tin.",
        
        // MacLehose Section 3
        "trail.c3d4e5f6-a7b8-9012-cdef-345678901234.name": "MacLehose Section 3",
        "trail.c3d4e5f6-a7b8-9012-cdef-345678901234.summary": "Challenging climb from Pak Tam Au to Kei Ling Ha over Kai Kung Shan.",
        
        // MacLehose Section 5
        "trail.d4e5f6a7-b8c9-0123-def0-456789012345.name": "MacLehose Section 5",
        "trail.d4e5f6a7-b8c9-0123-def0-456789012345.summary": "From Tate's Cairn to Tai Po Road via Lion Rock and Beacon Hill.",
        
        // MacLehose Section 6
        "trail.e4f5a6b7-c8d9-0123-ef01-456789012345.name": "MacLehose Section 6",
        "trail.e4f5a6b7-c8d9-0123-ef01-456789012345.summary": "From Tai Po Road to Shing Mun Reservoir.",
        
        // MacLehose Section 7
        "trail.f2a3b4c5-d6e7-8901-bcde-f23456789012.name": "MacLehose Section 7",
        "trail.f2a3b4c5-d6e7-8901-bcde-f23456789012.summary": "From Shing Mun Reservoir, steep climb up Needle Hill and Grassy Hill, then descend to Lead Mine Pass.",
        
        // MacLehose Section 8
        "trail.e5f6a7b8-c9d0-1234-ef01-567890123456.name": "MacLehose Section 8",
        "trail.e5f6a7b8-c9d0-1234-ef01-567890123456.summary": "Climb to Hong Kong's highest peak Tai Mo Shan from Lead Mine Pass.",
        
        // MacLehose Section 9
        "trail.f3a4b5c6-d7e8-9012-cdef-345678901234.name": "MacLehose Section 9",
        "trail.f3a4b5c6-d7e8-9012-cdef-345678901234.summary": "From Route Twisk, enter the plantation area of Tai Lam Country Park, heading towards Tin Fu Tsai.",
        
        // Wilson Trail Section 1
        "trail.f6a7b8c9-d0e1-2345-f012-678901234567.name": "Wilson Trail Section 1",
        "trail.f6a7b8c9-d0e1-2345-f012-678901234567.summary": "From Stanley Gap Road to Tsz Lo Lan Shan via Violet Hill and The Twins.",
        
        // Wilson Trail Section 2
        "trail.a7b8c9d0-e1f2-3456-0123-789012345678.name": "Wilson Trail Section 2",
        "trail.a7b8c9d0-e1f2-3456-0123-789012345678.summary": "From Tsz Lo Lan to Quarry Bay via Mount Butler and Jardine's Lookout.",
        
        // Lantau Trail Section 2
        "trail.b8c9d0e1-f2a3-4567-1234-890123456789.name": "Lantau Trail Section 2",
        "trail.b8c9d0e1-f2a3-4567-1234-890123456789.summary": "From Nam Shan to Pak Kung Au via Sunset Peak, Hong Kong's third highest peak.",
        
        // Lantau Trail Section 3
        "trail.c9d0e1f2-a3b4-5678-2345-901234567890.name": "Lantau Trail Section 3",
        "trail.c9d0e1f2-a3b4-5678-2345-901234567890.summary": "From Pak Kung Au to Ngong Ping via Lantau Peak, Hong Kong's second highest peak.",
        
        // Hong Kong Trail Section 1
        "trail.d0e1f2a3-b4c5-6789-3456-012345678901.name": "Hong Kong Trail Section 1",
        "trail.d0e1f2a3-b4c5-6789-3456-012345678901.summary": "From The Peak to Pok Fu Lam Reservoir via Lugard Road and Harlech Road.",
        
        // Hong Kong Trail Section 4
        "trail.e1f2a3b4-c5d6-7890-4567-123456789012.name": "Hong Kong Trail Section 4",
        "trail.e1f2a3b4-c5d6-7890-4567-123456789012.summary": "From Wan Chai Gap to Wong Nai Chung Gap via Black's Link and Jardine's Lookout.",
        
        // Lion Rock
        "trail.f2a3b4c5-d6e7-8901-5678-234567890123.name": "Lion Rock",
        "trail.f2a3b4c5-d6e7-8901-5678-234567890123.summary": "Iconic peak hike with panoramic views of Kowloon and Hong Kong Island.",
        
        // Sunset Peak
        "trail.a3b4c5d6-e7f8-9012-6789-345678901234.name": "Sunset Peak",
        "trail.a3b4c5d6-e7f8-9012-6789-345678901234.summary": "Climb to Sunset Peak via Mui Wo, famous for sunrise and sunset views.",
        
        // Sharp Peak
        "trail.b4c5d6e7-f8a9-0123-7890-456789012345.name": "Sharp Peak",
        "trail.b4c5d6e7-f8a9-0123-7890-456789012345.summary": "Challenging peak in Sai Kung East Country Park with distinctive pyramid shape.",
        
        // Tai Mo Shan
        "trail.c5d6e7f8-a9b0-1234-8901-567890123456.name": "Tai Mo Shan",
        "trail.c5d6e7f8-a9b0-1234-8901-567890123456.summary": "Hong Kong's highest peak at 957m, accessible via multiple routes.",
        
        // The Peak Circle Walk
        "trail.d6e7f8a9-b0c1-2345-9012-678901234567.name": "The Peak Circle Walk",
        "trail.d6e7f8a9-b0c1-2345-9012-678901234567.summary": "Easy circular walk around The Peak with stunning city and harbor views.",
        
        // Tai Tam Reservoir
        "trail.e7f8a9b0-c1d2-3456-0123-789012345678.name": "Tai Tam Reservoir",
        "trail.e7f8a9b0-c1d2-3456-0123-789012345678.summary": "Scenic walk around Tai Tam Reservoir with historic dam structures.",
        
        // Planner
        "planner.title": "Planner",
        "planner.choose.trail": "Choose trail",
        "planner.schedule": "Schedule",
        "planner.date": "Date",
        "planner.note": "Note (meet point, gear...)",
        "planner.preview": "Preview",
        "planner.select.trail": "Select a trail to see summary",
        "planner.saved": "Plan saved",
        "planner.saved.message": "Your hike has been added to your plans.",
        
        // Safety
        "safety.progress": "Progress",
        "safety.all.complete": "Great! You're all set for a safe hike.",
        "safety.complete.all": "Complete all items before heading out.",
        "safety.checklist.title": "Safety checklist",
        "safety.create.items": "Create Checklist Items",
        "safety.loading": "Loading checklist...",
        "safety.add.item": "Add Item",
        "safety.item.title": "Item Title",
        "safety.item.title.placeholder": "Enter item title",
        "safety.item.title.required": "Item title is required",
        "safety.item.icon": "Icon",
        "safety.item.save.error": "Failed to save item",
        "safety.item.location": "Enable Live Location",
        "safety.item.water": "Pack 2L of water",
        "safety.item.heat": "Check heat stroke signal",
        "safety.item.offline": "Download offline map",
        "safety.item.share": "Share hike plan with buddies",
        
        // Trail Alerts
        "alerts.no.active": "No Active Alerts",
        "alerts.all.clear": "All trails are clear. Enjoy your hike!",
        "alerts.critical": "Critical",
        "alerts.active": "Active Alerts",
        "alert.category.weather": "Weather",
        "alert.category.maintenance": "Maintenance",
        "alert.category.safety": "Safety",
        "alert.category.closure": "Closure",
        "alert.severity.low": "Low",
        "alert.severity.medium": "Medium",
        "alert.severity.high": "High",
        "alert.severity.critical": "Critical",
        "alert.time.minutes.ago": "min ago",
        "alert.time.hours.ago": "hours ago",
        "alert.time.days.ago": "days ago",
        "alert.issued.at": "Issued",
        "alert.updated.at": "Updated",
        "alert.title.route.maintenance": "Route Maintenance",
        "alert.title.weather": "Weather Alert",
        "alert.title.safety": "Safety Alert",
        "alert.title.closure": "Trail Closure",
        "alert.detail.maclehose.section2.maintenance": "Section 2 of MacLehose Trail is partially closed near Long Ke due to slope works. Alternative route available.",
        "alert.history.title": "Warning History",
        "alert.history.empty": "No warning history",
        "alert.history.description": "View past weather warnings and alerts",
        "alert.history.filter.all": "All",
        "alert.history.filter.active": "Active",
        "alert.history.filter.cancelled": "Cancelled",
        "alert.cancelled": "Cancelled",
        
        // Hike Plan
        "hike.plan.title": "Hike plan",
        "hike.plan.status": "Status",
        "hike.plan.mark.completed": "Mark as completed",
        "hike.plan.completed.on": "Completed on",
        "hike.plan.update": "Update plan",
        "hike.plan.delete": "Delete plan",
        "hike.plan.delete.message": "This hike will be removed from your planner.",
        
        // Hike Tracking
        "tracking.title": "Hike Tracking",
        "tracking.time": "Time",
        "tracking.distance": "Distance",
        "tracking.speed": "Speed",
        "tracking.altitude": "Altitude",
        "tracking.track.points": "Track Points",
        "tracking.select.trail": "Select Trail",
        "hike.tracking.select.trail": "Select Trail",
        "hike.tracking.start": "Start Tracking",
        
        // Hike Records
        "records.title": "Hike Records",
        "records.no.records": "No Hike Records",
        "records.start.tracking": "Start tracking your hiking activities to create records",
        "hike.records.feature.list": "Hike Records List",
        "hike.records.feature.list.desc": "View all your saved hike records",
        "hike.records.feature.detail": "Record Details",
        "hike.records.feature.detail.desc": "View detailed statistics, map and elevation profile",
        "hike.records.feature.playback": "3D Track Playback",
        "hike.records.feature.playback.desc": "Replay your hike track in 3D map",
        "records.detail": "Hike Record",
        "records.route.track": "Route Track",
        "records.no.track.data": "No Track Data",
        "records.detailed.stats": "Detailed Statistics",
        "records.max.speed": "Max Speed",
        "records.max.altitude": "Max Altitude",
        "records.min.altitude": "Min Altitude",
        "records.elev.loss": "Elev Loss",
        "records.track.points": "Track Points",
        "records.elevation.profile": "Elevation Profile",
        "records.insufficient.data": "Insufficient Data",
        "records.3d.playback": "3D Track Playback",
        "records.delete": "Delete Record",
        "records.delete.confirm": "Are you sure you want to delete this hike record? This action cannot be undone.",
        "records.distance": "Distance",
        "records.duration": "Duration",
        "records.avg.speed": "Avg Speed",
        "records.elev.gain": "Elev Gain",
        "records.start": "Start",
        "records.end": "End",
        "records.unit.km": "km",
        "records.unit.kmh": "km/h",
        "records.unit.m": "m",
        
        // Location Sharing
        "location.sharing.title": "Location Sharing",
        "location.sharing.sharing": "Sharing Location",
        "location.sharing.not.sharing": "Not Sharing",
        "location.sharing.description": "Your real-time location is being shared with emergency contacts",
        "location.sharing.start.description": "Tap the button below to start sharing location",
        "location.sharing.start": "Start Sharing",
        "location.sharing.stop": "Stop Sharing",
        "location.sharing.sos": "Emergency SOS",
        "location.sharing.anomaly": "Anomaly Detection",
        "location.sharing.detected.at": "Detected at",
        "location.sharing.current.location": "Current Location",
        "location.sharing.latitude": "Latitude",
        "location.sharing.longitude": "Longitude",
        "location.sharing.altitude": "Altitude",
        "location.sharing.share.link": "Share Link",
        "location.sharing.copy.link": "Copy Link",
        "location.sharing.contacts": "Emergency Contacts",
        "location.sharing.no.contacts": "No Emergency Contacts",
        "location.sharing.add.contact.description": "Please add at least one emergency contact to use location sharing and emergency SOS features",
        "location.sharing.add.contact": "Add Emergency Contact",
        "location.sharing.contact.info": "Contact Information",
        "location.sharing.name": "Name",
        "location.sharing.phone": "Phone Number",
        "location.sharing.email": "Email (Optional)",
        "location.sharing.primary": "Primary",
        "location.sharing.sos.confirm": "Confirm Emergency SOS",
        "location.sharing.sos.message": "This will send your location and SOS message to all emergency contacts. Please confirm this is an emergency.",
        "location.sharing.send": "Send",
        
        // Species Identification
        "species.title": "Species Identification",
        "species.identifying": "Identifying...",
        "species.take.photo": "Take Photo",
        "species.photo.library": "Photo Library",
        "species.habitat": "Habitat",
        "species.distribution": "Distribution",
        "species.other.possibilities": "Other Possibilities",
        "species.unable.to.identify": "Unable to Identify",
        "species.history": "Identification History",
        "species.no.history": "No Identification History",
        "species.start.identifying": "Start identifying species to view history",
        
        // Recommendations
        "recommendations.title": "Trail Recommendations",
        "recommendations.settings": "Recommendation Settings",
        "recommendations.available.time": "Available Time",
        "recommendations.hours": "hours",
        "recommendations.half.hour": "30 minutes",
        "recommendations.hour.and.half": " hour 30 minutes",
        "recommendations.regenerate": "Regenerate Recommendations",
        "recommendations.no.recommendations": "No Recommendations",
        "recommendations.adjust.preferences": "Please adjust your preferences or available time",
        "recommendations.for.you": "Recommended for You",
        "recommendations.match": "Match",
        "recommendations.view.details": "View Details",
        "recommendations.preferences": "Preferences",
        "recommendations.preferred.difficulty": "Preferred Difficulty",
        "recommendations.difficulty": "Difficulty",
        "recommendations.no.preference": "No Preference",
        "recommendations.preferred.distance": "Preferred Distance",
        "recommendations.min": "Min",
        "recommendations.max": "Max",
        
        // Journal
        "journal.title": "Journal",
        "journal.create": "Create Journal Entry",
        "journal.edit": "Edit Journal Entry",
        "journal.detail": "Journal Detail",
        "journal.new.entry": "New Journal Entry",
        "journal.basic.information": "Basic Information",
        "journal.title.field": "Title",
        "journal.hike.date": "Hike Date",
        "journal.trail": "Trail",
        "journal.location": "Location",
        "journal.select.trail": "Select Trail",
        "journal.change": "Change",
        "journal.content": "Content",
        "journal.photos": "Photos",
        "journal.add.photos": "Add Photos",
        "journal.delete.confirm": "Delete Journal Entry",
        "journal.delete.message": "Are you sure you want to delete this journal entry? This action cannot be undone.",
        "journal.share.date": "Date",
        "journal.share.trail": "Trail",
        "journal.share.weather": "Weather",
        "journal.share.shared.from": "Shared from Hiking HK",
        
        // Achievements
        "achievements.title": "Achievements & Badges",
        "achievements.unlocked": "Unlocked",
        "achievements.total": "Total",
        "achievements.new.unlocked": "New Achievement Unlocked!",
        "achievements.congratulations": "Congratulations! You unlocked the",
        "achievements.achievement": "achievement!",
        "achievements.unlocked.on": "Unlocked on",
        "achievements.filter.all": "All",
        
        // Gear Checklist
        "gear.title": "Smart Gear Checklist",
        "gear.view.checklist": "View Gear Checklist",
        "gear.progress": "Progress",
        "gear.required": "Required",
        "gear.required.items": "Required Items",
        "gear.all.required.complete": "All required items completed!",
        "gear.no.items": "No Gear Items",
        "gear.generate.description": "Gear list will be generated based on trail difficulty, weather, and season",
        "gear.category.essential": "Essential",
        "gear.category.clothing": "Clothing",
        "gear.category.navigation": "Navigation",
        "gear.category.safety": "Safety",
        "gear.category.food": "Food",
        "gear.category.tools": "Tools",
        "gear.category.optional": "Optional",
        
        // Gear Item Names
        "gear.item.water.bottle": "Water Bottle (2L minimum)",
        "gear.item.extra.water": "Extra Water (1L per additional 2 hours)",
        "gear.item.mobile.phone": "Mobile Phone (fully charged)",
        "gear.item.power.bank": "Power Bank",
        "gear.item.id.card": "ID Card / ID Document",
        "gear.item.moisture.tshirt": "Moisture-wicking T-shirt",
        "gear.item.hiking.pants": "Hiking Pants / Shorts",
        "gear.item.hiking.shoes": "Hiking Shoes / Boots",
        "gear.item.socks": "Socks (extra pair)",
        "gear.item.warm.jacket": "Warm Jacket / Fleece",
        "gear.item.beanie": "Beanie / Warm Hat",
        "gear.item.sun.hat": "Sun Hat / Cap",
        "gear.item.sunglasses": "Sunglasses",
        "gear.item.rain.jacket": "Rain Jacket / Poncho",
        "gear.item.uv.protection": "UV Protection Clothing",
        "gear.item.offline.map": "Offline Map (downloaded)",
        "gear.item.compass": "Compass",
        "gear.item.gps.device": "GPS Device (optional backup)",
        "gear.item.first.aid": "First Aid Kit",
        "gear.item.whistle": "Whistle",
        "gear.item.emergency.blanket": "Emergency Blanket",
        "gear.item.headlamp": "Headlamp / Flashlight",
        "gear.item.sunscreen": "Sunscreen (SPF 50+)",
        "gear.item.insect.repellent": "Insect Repellent",
        "gear.item.energy.snacks": "Energy Snacks",
        "gear.item.light.meal": "Light Meal / Sandwich",
        "gear.item.full.meal": "Full Meal",
        "gear.item.electrolyte.drink": "Electrolyte Drinks / Sports Drink",
        "gear.item.electrolyte.tablets": "Electrolyte Tablets",
        "gear.item.multi.tool": "Multi-tool / Knife",
        "gear.item.trekking.poles": "Trekking Poles",
        "gear.item.camera": "Camera",
        "gear.item.binoculars": "Binoculars",
        "gear.item.lightweight.gloves": "Lightweight Gloves",
        
        // Offline Maps
        "offline.maps.no.regions": "No regions available",
        "offline.maps.available.regions": "Available Regions",
        "offline.maps.create.regions": "Create Map Regions",
        "offline.maps.loading": "Loading regions...",
        "offline.maps.total.downloaded": "Total downloaded",
        "offline.maps.clear.all": "Clear All Downloads",
        "offline.maps.downloading": "Downloading...",
        "offline.maps.download.error": "Download Error",
        "offline.maps.region.hong.kong.island": "Hong Kong Island",
        "offline.maps.region.kowloon.ridge": "Kowloon Ridge",
        "offline.maps.region.sai.kung.east": "Sai Kung East",
        "offline.maps.region.lantau.north": "Lantau North",
        "offline.maps.status.not.downloaded": "Not Downloaded",
        "offline.maps.status.downloading": "Downloading",
        "offline.maps.status.downloaded": "Downloaded",
        "offline.maps.status.failed": "Failed",
        "offline.maps.status.updating": "Updating",
        "offline.maps.delete.confirm": "Delete Offline Map",
        "offline.maps.delete.message": "Are you sure you want to delete this offline map? This action cannot be undone.",
        
        // AR Identify
        "ar.scanning.skyline": "Scanning skyline…",
        "ar.found": "Found",
        "ar.point.camera": "Point your camera at a ridge to identify peaks",
        "ar.searching.landmarks": "Searching for landmarks...",
        "ar.recent.identifications": "Recent Identifications",
        "ar.no.landmarks": "No landmarks identified yet",
        "ar.start.scanning": "Start scanning to identify nearby peaks",
        "ar.start.scan": "Start Scan",
        "ar.stop.scan": "Stop Scan",
        
        // Location Sharing (additional)
        "location.share.confirm.sos": "Confirm Emergency SOS",
        "location.share.sos.message": "This will send your location and SOS message to all emergency contacts. Please confirm this is an emergency.",
        "location.share.sharing": "Sharing Location",
        "location.share.not.sharing": "Not Sharing",
        "location.share.start": "Start Sharing",
        "location.share.stop": "Stop Sharing",
        "location.share.send": "Send",
        "location.share.sharing.description": "Your real-time location is being shared with emergency contacts",
        "location.share.start.description": "Tap the button below to start sharing location",
        "location.share.anomaly.detection": "Anomaly Detection",
        "location.share.detected.at": "Detected at",
        "location.share.current.location": "Current Location",
        "location.share.latitude": "Latitude",
        "location.share.longitude": "Longitude",
        "location.share.altitude": "Altitude",
        "location.share.share.link": "Share Link",
        "location.share.copy.link": "Copy Link",
        "location.share.emergency.sos": "Emergency SOS",
        "location.share.emergency.contacts": "Emergency Contacts",
        "location.share.no.emergency.contacts": "No Emergency Contacts",
        "location.share.add.contact.description": "Please add at least one emergency contact to use location sharing and emergency SOS features",
        "location.share.add.emergency.contact": "Add Emergency Contact",
        "location.share.contact.information": "Contact Information",
        "location.share.contact.name": "Name",
        "location.share.contact.phone": "Phone Number",
        "location.share.contact.email": "Email (Optional)",
        "location.share.primary": "Primary",
        "location.share.simulator.warning.title": "Simulator Location Detected",
        "location.share.simulator.warning.message": "The current location appears to be the iOS Simulator default (San Francisco). Please set a custom location in the Simulator: Features > Location > Custom Location, or test on a real device.",
        "error": "Error",
        
        // Hike Records (additional)
        "hike.records.none": "No Hike Records",
        "hike.records.start.tracking": "Start tracking your hiking activities to create records",
        "hike.records.unnamed.trail": "Unnamed Trail",
        
        // Hike Tracking (additional)
        "hike.tracking.title": "Hike Tracking",
        "hike.tracking.time": "Time",
        "hike.tracking.distance": "Distance",
        "hike.tracking.speed": "Speed",
        "hike.tracking.altitude": "Altitude",
        "hike.tracking.track.points": "Track Points",
        "hike.tracking.current.location": "Current Location",
        
        // Recommendations (additional)
        "recommendations.generating": "Generating recommendations...",
        
        // Preferences
        "preferences.title": "Preferences",
        "preferences.fitness.level": "Fitness Level",
        "preferences.scenery": "Preferred Scenery",
        "preferences.difficulty": "Preferred Difficulty",
        "preferences.distance": "Preferred Distance",
        "preferences.min": "Min",
        "preferences.max": "Max",
        "preferences.no.preference": "No Preference",
        "preferences.fitness.level.初學者": "Beginner",
        "preferences.fitness.level.中級": "Intermediate",
        "preferences.fitness.level.高級": "Advanced",
        "preferences.fitness.level.專家": "Expert",
        "preferences.scenery.海景": "Sea View",
        "preferences.scenery.山景": "Mountain View",
        "preferences.scenery.森林": "Forest",
        "preferences.scenery.水庫": "Reservoir",
        "preferences.scenery.城市景觀": "City View",
        "preferences.scenery.日落": "Sunset",
        "preferences.scenery.日出": "Sunrise",
        
        // Species Identification (additional)
        "species.identification.title": "Species Identification",
        "species.identification.identifying": "Identifying...",
        "species.identification.take.photo": "Take Photo",
        "species.identification.photo.library": "Photo Library",
        "species.identification.habitat": "Habitat",
        
        // Journal (additional)
        "journal.list.title": "Hiking Journal",
        "journal.no.entries": "No Journal Entries",
        "journal.start.documenting": "Start documenting your hiking adventures!",
        "journal.create.first.entry": "Create First Entry",
        "journal.save.error": "Save Error",
        
        // Anomaly Severity
        "anomaly.severity.low": "Low",
        "anomaly.severity.medium": "Medium",
        "anomaly.severity.high": "High",
        "anomaly.severity.critical": "Critical",
        
        // MTR Real-time Schedule
        "mtr.real.time.schedule": "MTR Real-time Train Schedule",
        "mtr.direction.up": "Up",
        "mtr.direction.down": "Down",
        "mtr.arriving": "Arriving",
        "mtr.minutes": "min",
        "mtr.error.load.failed": "Unable to load train schedule",
        
        // Transport
        "transport.title": "Transport",
        "transport.mtr": "MTR",
        "transport.bus": "Bus",
        "transport.search": "Search",
        "transport.mtr.search.title": "Search MTR Station",
        "transport.mtr.search.placeholder": "Enter station name (e.g., Tsuen Wan)",
        "transport.mtr.quick.stations": "Quick Select:",
        "transport.mtr.no.schedule": "No schedule available",
        "transport.mtr.station.not.found": "Station not found. Please try: Tsuen Wan, Shau Kei Wan, Central, Admiralty, Tung Chung, Kwun Tong",
        "transport.bus.search.title": "Search Bus Route",
        "transport.bus.search.placeholder": "Enter route number or station name",
        "transport.bus.no.results": "No results found",
        "transport.bus.results": "Search Results",
        "transport.bus.routes.found": "routes found",
        "transport.bus.showing.first.20": "Showing first 20 results",
        "transport.bus.stops": "Bus Stops",
        "transport.bus.eta": "Estimated Arrival Time",
        "transport.bus.real.time.eta": "Real-time Arrival",
        "transport.bus.loading.eta": "Loading...",
        "transport.bus.outbound": "Outbound",
        "transport.bus.inbound": "Inbound",
        "transport.bus.error.load.failed": "Unable to load bus information",
        
        // Home Quick Actions
        "home.transport": "Transport"
    ]
    
    private static let traditionalChineseStrings: [String: String] = [
        // Common
        "app.name": "行山香港",
        "ok": "確定",
        "cancel": "取消",
        "save": "儲存",
        "delete": "刪除",
        "edit": "編輯",
        "close": "關閉",
        "start": "開始",
        "stop": "停止",
        "pause": "暫停",
        "resume": "繼續",
        "done": "完成",
        
        // Auth
        "auth.name": "姓名",
        "auth.email": "電子郵件",
        "auth.password": "密碼",
        "auth.create.account": "創建您的行山帳戶。",
        "auth.sign.in.description": "登入以同步您的行山記錄、徽章和計劃。",
        "auth.create.account.button": "創建帳戶",
        "auth.sign.in": "登入",
        "auth.have.account": "已有帳戶？登入",
        "auth.new.hiker": "新行山者？創建帳戶",
        "auth.preparing.storage": "正在準備安全儲存…",
        "auth.quick.accounts": "快速帳戶",
        
        // Profile
        "profile.title": "個人資料",
        "profile.account": "帳戶",
        "profile.stats": "統計",
        "profile.achievements": "成就",
        "profile.achievements.badges": "成就與徽章",
        "profile.goals": "目標",
        
        // Achievements
        "achievement.unlocked": "已解鎖",
        "achievement.total": "總數",
        "achievement.filter.all": "全部",
        "achievement.badge.type.distance": "距離",
        "achievement.badge.type.peaks": "山峰",
        "achievement.badge.type.streak": "連續",
        "achievement.badge.type.exploration": "探索",
        "achievement.unlocked.on": "解鎖於",
        "achievement.new.unlocked": "新成就已解鎖！",
        "achievement.view": "查看",
        "achievement.congratulations": "恭喜！您解鎖了「{title}」成就！",
        
        // Achievement Titles and Descriptions
        "achievement.distance_10km.title": "初級行山者",
        "achievement.distance_10km.description": "完成10公里行山",
        "achievement.distance_50km.title": "行山愛好者",
        "achievement.distance_50km.description": "完成50公里行山",
        "achievement.distance_100km.title": "行山專家",
        "achievement.distance_100km.description": "完成100公里行山",
        "achievement.distance_500km.title": "行山大師",
        "achievement.distance_500km.description": "完成500公里行山",
        "achievement.peak_lion_rock.title": "獅子山征服者",
        "achievement.peak_lion_rock.description": "登頂獅子山",
        "achievement.peak_tai_mo_shan.title": "大帽山征服者",
        "achievement.peak_tai_mo_shan.description": "登頂大帽山（香港最高峰）",
        "achievement.peak_sunset_peak.title": "鳳凰山征服者",
        "achievement.peak_sunset_peak.description": "登頂鳳凰山（大嶼山）",
        "achievement.peak_sharp_peak.title": "蚺蛇尖征服者",
        "achievement.peak_sharp_peak.description": "登頂蚺蛇尖",
        "achievement.peak_4_peaks.title": "四峰征服者",
        "achievement.peak_4_peaks.description": "登頂4座不同的山峰",
        "achievement.streak_1_week.title": "一週連續",
        "achievement.streak_1_week.description": "連續7天行山",
        "achievement.streak_2_weeks.title": "兩週連續",
        "achievement.streak_2_weeks.description": "連續14天行山",
        "achievement.streak_1_month.title": "月度連續",
        "achievement.streak_1_month.description": "連續30天行山",
        "achievement.explore_3_districts.title": "探索者",
        "achievement.explore_3_districts.description": "探索3個不同的地區",
        "achievement.explore_5_districts.title": "冒險家",
        "achievement.explore_5_districts.description": "探索5個不同的地區",
        "achievement.explore_10_districts.title": "探索大師",
        "achievement.explore_10_districts.description": "探索10個不同的地區",
        
        "profile.data.services": "數據與服務",
        "profile.language": "語言",
        "profile.language.description": "選擇您的偏好語言",
        "profile.sign.out": "登出",
        "profile.sign.out.confirm": "您確定要登出嗎？",
        
        // Stats
        "stats.planned": "已計劃",
        "stats.favorites": "收藏",
        "stats.logged": "已記錄",
        
        // Goals
        "goal.ridge_lines": "完成4條山脊線",
        "goal.monthly_distance": "本月記錄50公里",
        "goal.completed": "已完成",
        "goal.unit.km": "公里",
        "goal.unit.lines": "條",
        
        // Services
        "service.weather.api": "香港天文台天氣API",
        "service.csdi.api": "CSDI 地理資訊平台 API",
        "service.gps.tracking": "GPS追蹤",
        "service.offline.maps": "離線地圖",
        "service.mapbox.api": "Mapbox API",
        "service.status.connected": "已連接",
        "service.status.disconnected": "未連接",
        "service.status.unavailable": "不可用",
        "service.status.unknown": "未知",
        
        // Trails Data
        "profile.trails.data": "路線數據",
        "profile.trails.total": "路線總數",
        "profile.trails.loading": "正在從 API 加載路線...",
        "profile.trails.refresh": "刷新路線",
        "trails.loading": "正在加載路線...",
        
        // API Status
        "api.status.title": "API狀態",
        "api.status.last.checked": "最後檢查",
        "api.status.never": "從未",
        "api.status.check.connection": "檢查API連接",
        "api.status.checking": "檢查中...",
        "api.status.connected": "已連接",
        "api.status.disconnected": "未連接",
        "api.status.not.configured": "未配置",
        "api.status.error": "錯誤",
        
        // Home
        "home.title": "首頁",
        "home.quick.actions": "快捷操作",
        "home.trail.alerts": "路線警示",
        "home.offline.maps": "離線地圖",
        "home.ar.identify": "AR 識別",
        "home.location.share": "位置分享",
        "home.start.tracking": "開始追蹤",
        "home.hike.records": "行山記錄",
        "home.recommendations": "智能推薦",
        "home.species.id": "物種識別",
        "home.journal": "日記",
        "home.sos": "緊急求救",
        "home.sos.confirm": "這將打開位置分享功能，您可以在那裡發送緊急求救。",
        "home.sos.open.sharing": "打開位置分享",
        "home.featured.trail": "精選路線",
        "home.elev.gain": "海拔上升",
        "home.view.trail.plan": "查看路線計劃",
        "home.featured.add.to.plan.confirm": "加入即將計劃？",
        "home.featured.add.to.plan.message": "是否將此精選路線加入「即將計劃」？",
        "home.next.plans": "即將計劃",
        "home.add": "添加",
        "home.no.hikes.scheduled": "尚無計劃的行山",
        "home.tap.add.to.plan": "點擊添加以計劃您的第一次行山",
        "home.refresh.weather": "刷新天氣",
        "home.safety": "安全",
        "home.sos.button": "緊急求救",
        "home.weather.forecast": "天氣預測",
        "home.best.hiking.time": "最佳行山時間",
        
        // Weather
        "weather.location.hko": "香港天文台",
        "weather.location.kings.park": "京士柏",
        "weather.select.location": "選擇地區",
        "weather.forecast.title": "天氣預測",
        "weather.region": "地區",
        "weather.region.hong.kong.island": "香港島",
        "weather.region.kowloon": "九龍",
        "weather.region.new.territories": "新界",
        "weather.region.lantau": "大嶼山",
        "weather.forecast.best.times": "最佳行山時間",
        "weather.forecast.7day": "7天預測",
        "weather.forecast.9day": "9天天氣預報",
        "weather.view.9day.forecast": "查看九天天氣預報",
        "weather.forecast.today": "今天",
        "weather.forecast.comfort.index": "舒適度指數",
        "weather.forecast.precipitation": "降雨",
        "weather.forecast.no.best.times": "所選位置暫無最佳行山時間。",
        "weather.forecast.good.for.hiking": "適合行山",
        "weather.forecast.other.days": "其他日子",
        "weather.temperature": "溫度",
        "retry": "重試",
        "weather.humidity": "濕度",
        "weather.uv.index": "紫外線指數",
        
        // Weather Conditions
        "weather.condition.sunny": "晴天",
        "weather.condition.partly.cloudy": "部分多雲",
        "weather.condition.cloudy": "多雲",
        "weather.condition.overcast": "陰天",
        "weather.condition.light.rain": "小雨",
        "weather.condition.moderate.rain": "中雨",
        "weather.condition.heavy.rain": "大雨",
        "weather.condition.thunderstorm": "雷暴",
        "weather.condition.foggy": "有霧",
        "weather.condition.windy": "有風",
        "weather.error.cached": "無法載入最新天氣。顯示緩存數據。",
        "weather.suggestion.warning": "天氣警告生效。重新計劃或攜帶全套雨具。",
        "weather.suggestion.extreme.uv": "極高紫外線。建議清晨出發並攜帶防曬霜/雨傘。",
        "weather.suggestion.humid": "潮濕天氣。請頻繁補充水分並多休息。",
        "weather.suggestion.stable": "天氣狀況穩定，適合挑戰暴露的山脊路線。",
        "weather.suggestion.good": "部分多雲，微東風。正午前開始山脊行山的好時機。",
        
        // Trails
        "trails.title": "路線",
        "trails.details": "路線詳情",
        "trails.distance": "距離",
        "trails.duration": "時長",
        "trails.difficulty": "難度",
        "trails.district": "地區",
        "trails.elevation": "海拔",
        "trails.all.difficulties": "所有難度",
        "trails.search.prompt": "名稱或地區",
        "trail.checkpoints": "路線檢查點",
        "trail.facilities": "設施與服務",
        "trail.highlights": "亮點",
        "trail.transportation": "交通提示",
        "trail.start.point": "起點",
        "trail.end.point": "終點",
        "trail.supply.points": "補給點",
        "trail.exit.routes": "退出路線",
        "trail.notes": "注意事項",
        "trail.image.unavailable": "圖片無法載入",
        
        // Map
        "map.interactive": "交互式地圖",
        "map.start": "起點",
        "map.you": "您的位置",
        "map.start.location": "起點 {district}",
        "map.enable.location": "啟用位置",
        "map.center.on.me": "定位到我的位置",
        "map.location.disabled": "位置已禁用",
        "map.mapbox.token.required": "設置 MAPBOX_ACCESS_TOKEN 以查看實時路線疊加層。",
        "map.offline.mode": "離線模式",
        "map.offline.available": "離線地圖可用",
        "map.using.offline": "使用離線地圖",
        "map.distance.post": "標距柱",
        "map.distance.post.number": "標距柱 {number}",
        
        // Distance Posts
        "distance.posts.title": "標距柱",
        "distance.posts.post.number": "標距柱 {number}",
        "distance.posts.distance.from.start": "距離起點 {distance} 公里",
        "distance.posts.no.posts": "此路線暫無標距柱資料",
        "distance.posts.loading": "載入標距柱資料中...",
        
        // Checkpoints
        "checkpoint.trailhead": "起點",
        "checkpoint.viewpoint": "觀景點",
        "checkpoint.finish": "終點",
        "checkpoint.peak": "山峰",
        "checkpoint.start": "起點",
        "checkpoint.photo.spot": "拍照點",
        "checkpoint.starting.point": "起點",
        "checkpoint.photo.stop": "拍照點",
        "checkpoint.halfway.point": "中點",
        
        // Dragon's Back Checkpoints
        "checkpoint.to.tei.wan": "土地灣",
        "checkpoint.dragons.back.ridge": "龍脊",
        "checkpoint.big.wave.bay": "大浪灣",
        "checkpoint.ng.tung.chai": "梧桐寨",
        "checkpoint.bottom.fall": "下瀑布",
        "checkpoint.main.fall": "主瀑布",
        
        // Facilities
        "facility.country.park.toilet": "郊野公園洗手間",
        "facility.pavilion.shelter": "涼亭",
        "facility.visitor.center": "訪客中心",
        "facility.toilet": "洗手間",
        "facility.camping": "露營",
        "facility.big.wave.bay.showers": "大浪灣淋浴設施",
        "facility.water.kiosks": "水站",
        "facility.village.stores": "村莊商店",
        "facility.taxi.stand": "的士站",
        
        // Checkpoint Names (MacLehose Section 4)
        "checkpoint.kei.ling.ha": "企嶺下",
        "checkpoint.kai.kung.shan": "雞公山",
        "checkpoint.tates.cairn": "基維爾營",
        "checkpoint.high.island.reservoir": "萬宜水庫",
        "checkpoint.sharp.peak": "蚺蛇尖",
        "checkpoint.tai.long.wan": "大浪灣",
        "checkpoint.route.twisk": "荃錦公路",
        "checkpoint.tai.mo.shan": "大帽山",
        "checkpoint.lead.mine.pass": "鉛礦坳",
        "checkpoint.nam.shan": "南山",
        "checkpoint.pak.kung.au": "伯公坳",
        "checkpoint.ngong.ping": "昂坪",
        "checkpoint.the.peak": "山頂",
        "checkpoint.pok.fu.lam.reservoir": "薄扶林水塘",
        "checkpoint.wan.chai.gap": "灣仔峽",
        "checkpoint.wong.nai.chung.gap": "黃泥涌峽",
        "checkpoint.lion.rock.park": "獅子山公園",
        "checkpoint.mui.wo": "梅窩",
        "checkpoint.pak.tam.chung": "北潭涌",
        "checkpoint.stanley.gap": "赤柱峽",
        "checkpoint.tai.tam": "大潭",
        "checkpoint.stanley": "赤柱",
        
        // Tai Mo Shan Waterfalls Trail
        "trail.b0f98fdf-2f2f-4c19-a032-654b2c73e0b7.highlight.main.fall.35.m.drop": "主瀑布 35 米落差",
        "trail.b0f98fdf-2f2f-4c19-a032-654b2c73e0b7.highlight.shaded.bamboo.forest": "陰涼竹林",
        "trail.b0f98fdf-2f2f-4c19-a032-654b2c73e0b7.highlight.stream.play.area": "溪流遊樂區",
        "trail.b0f98fdf-2f2f-4c19-a032-654b2c73e0b7.transportation": "乘搭 64K/64P 巴士前往梧桐寨村；回程路線相同。",
        
        // Units
        "unit.km": "公里",
        "unit.m": "米",
        "unit.h": "小時",
        
        // Trail Difficulties
        "trail.difficulty.easy": "容易",
        "trail.difficulty.moderate": "中等",
        "trail.difficulty.challenging": "困難",
        
        // Trail Districts
        "trail.district.sai.kung": "西貢",
        "trail.district.hong.kong.island": "香港島",
        "trail.district.tsuen.wan": "荃灣",
        "trail.district.sha.tin": "沙田",
        "trail.district.tai.mo.shan": "大帽山",
        "trail.district.kowloon": "九龍",
        "trail.district.lantau": "大嶼山",
        "trail.district.tai.po": "大埔",
        "trail.district.new.territories.central": "新界中部",
        "trail.district.new.territories.northwest": "新界西北",
        
        // Trail Names and Summaries (MacLehose Section 4)
        "trail.0c8c0a67-9b84-4d4e-8f1c-2b7b4e3eb7a0.name": "麥理浩徑第四段",
        "trail.0c8c0a67-9b84-4d4e-8f1c-2b7b4e3eb7a0.summary": "從企嶺下到基維爾營的標誌性山脊步道，可欣賞西貢海的全景。",
        "trail.0c8c0a67-9b84-4d4e-8f1c-2b7b4e3eb7a0.transportation": "乘搭 99/99R 巴士到企嶺下；回程從基維爾隧道口乘搭巴士/小巴。",
        "trail.0c8c0a67-9b84-4d4e-8f1c-2b7b4e3eb7a0.highlight.sharp.peak.vista": "蚺蛇尖景觀",
        "trail.0c8c0a67-9b84-4d4e-8f1c-2b7b4e3eb7a0.highlight.ma.on.shan.country.park.geology": "馬鞍山郊野公園地質",
        "trail.0c8c0a67-9b84-4d4e-8f1c-2b7b4e3eb7a0.highlight.golden.hour.sunrise.spot": "黃金時段日出觀賞點",
        
        // Dragon's Back
        "trail.7d62f08b-24af-4da4-95bb-818e0c1cd2b5.name": "龍脊",
        "trail.7d62f08b-24af-4da4-95bb-818e0c1cd2b5.summary": "最受歡迎的半日行山路線，可欣賞石澳、大浪灣和赤柱的沿海風景。",
        "trail.7d62f08b-24af-4da4-95bb-818e0c1cd2b5.transportation": "港鐵筲箕灣站 → 9號巴士至土地灣；回程從大浪灣乘巴士/小巴離開。",
        "trail.7d62f08b-24af-4da4-95bb-818e0c1cd2b5.highlight.shek.o.peninsula.lookout": "石澳半島觀景台",
        "trail.7d62f08b-24af-4da4-95bb-818e0c1cd2b5.highlight.paragliding.take-off.site": "滑翔傘起飛點",
        "trail.7d62f08b-24af-4da4-95bb-818e0c1cd2b5.highlight.surfing.beach.finale": "衝浪海灘終點",
        
        // Tai Mo Shan Waterfalls
        "trail.b0f98fdf-2f2f-4c19-a032-654b2c73e0b7.name": "大帽山瀑布",
        "trail.b0f98fdf-2f2f-4c19-a032-654b2c73e0b7.summary": "適合家庭的自然步道，展示梧桐寨瀑布群的四個主要瀑布。",
        
        // MacLehose Section 1
        "trail.a1b2c3d4-e5f6-7890-abcd-ef1234567890.name": "麥理浩徑第一段",
        "trail.a1b2c3d4-e5f6-7890-abcd-ef1234567890.summary": "從北潭涌到浪茄灣的輕鬆沿海步道，可欣賞水庫景色。",
        
        // MacLehose Section 2
        "trail.b2c3d4e5-f6a7-8901-bcde-f23456789012.name": "麥理浩徑第二段",
        "trail.b2c3d4e5-f6a7-8901-bcde-f23456789012.summary": "從浪茄到北潭凹的風景路線，途經西灣和鹹田灣。",
        
        // MacLehose Section 3
        "trail.c3d4e5f6-a7b8-9012-cdef-345678901234.name": "麥理浩徑第三段",
        "trail.c3d4e5f6-a7b8-9012-cdef-345678901234.summary": "從北潭凹到企嶺下的挑戰性攀登路線，途經雞公山。",
        
        // MacLehose Section 5
        "trail.d4e5f6a7-b8c9-0123-def0-456789012345.name": "麥理浩徑第五段",
        "trail.d4e5f6a7-b8c9-0123-def0-456789012345.summary": "從基維爾營到大埔公路，途經獅子山和筆架山。",
        
        // MacLehose Section 6
        "trail.e4f5a6b7-c8d9-0123-ef01-456789012345.name": "麥理浩徑第六段",
        "trail.e4f5a6b7-c8d9-0123-ef01-456789012345.summary": "從大埔公路到城門水塘。",
        
        // MacLehose Section 7
        "trail.f2a3b4c5-d6e7-8901-bcde-f23456789012.name": "麥理浩徑第七段",
        "trail.f2a3b4c5-d6e7-8901-bcde-f23456789012.summary": "從城門水塘出發，急攀針山與草山後，下降至鉛礦坳。",
        
        // MacLehose Section 8
        "trail.e5f6a7b8-c9d0-1234-ef01-567890123456.name": "麥理浩徑第八段",
        "trail.e5f6a7b8-c9d0-1234-ef01-567890123456.summary": "從鉛礦坳攀登至香港最高峰大帽山。",
        
        // MacLehose Section 9
        "trail.f3a4b5c6-d7e8-9012-cdef-345678901234.name": "麥理浩徑第九段",
        "trail.f3a4b5c6-d7e8-9012-cdef-345678901234.summary": "從荃錦公路出發，進入大欖郊野公園的植林區，往田夫仔進發。",
        
        // Wilson Trail Section 1
        "trail.f6a7b8c9-d0e1-2345-f012-678901234567.name": "衛奕信徑第一段",
        "trail.f6a7b8c9-d0e1-2345-f012-678901234567.summary": "從黃泥涌峽道到紫羅蘭山，途經紫崗橋和孖崗山。",
        
        // Wilson Trail Section 2
        "trail.a7b8c9d0-e1f2-3456-0123-789012345678.name": "衛奕信徑第二段",
        "trail.a7b8c9d0-e1f2-3456-0123-789012345678.summary": "從紫羅蘭山到鰂魚涌，途經畢拿山和渣甸山。",
        
        // Lantau Trail Section 2
        "trail.b8c9d0e1-f2a3-4567-1234-890123456789.name": "鳳凰徑第二段",
        "trail.b8c9d0e1-f2a3-4567-1234-890123456789.summary": "從南山到伯公坳，途經香港第三高峰鳳凰山。",
        
        // Lantau Trail Section 3
        "trail.c9d0e1f2-a3b4-5678-2345-901234567890.name": "鳳凰徑第三段",
        "trail.c9d0e1f2-a3b4-5678-2345-901234567890.summary": "從伯公坳到昂坪，途經香港第二高峰大東山。",
        
        // Hong Kong Trail Section 1
        "trail.d0e1f2a3-b4c5-6789-3456-012345678901.name": "港島徑第一段",
        "trail.d0e1f2a3-b4c5-6789-3456-012345678901.summary": "從山頂到薄扶林水塘，途經盧吉道和夏力道。",
        
        // Hong Kong Trail Section 4
        "trail.e1f2a3b4-c5d6-7890-4567-123456789012.name": "港島徑第四段",
        "trail.e1f2a3b4-c5d6-7890-4567-123456789012.summary": "從灣仔峽到黃泥涌峽，途經布力徑和渣甸山。",
        
        // Lion Rock
        "trail.f2a3b4c5-d6e7-8901-5678-234567890123.name": "獅子山",
        "trail.f2a3b4c5-d6e7-8901-5678-234567890123.summary": "標誌性的山峰行山路線，可欣賞九龍和香港島的全景。",
        
        // Sunset Peak
        "trail.a3b4c5d6-e7f8-9012-6789-345678901234.name": "鳳凰山",
        "trail.a3b4c5d6-e7f8-9012-6789-345678901234.summary": "從梅窩攀登至鳳凰山，以日出和日落景色聞名。",
        
        // Sharp Peak
        "trail.b4c5d6e7-f8a9-0123-7890-456789012345.name": "蚺蛇尖",
        "trail.b4c5d6e7-f8a9-0123-7890-456789012345.summary": "西貢東郊野公園的挑戰性山峰，具有獨特的金字塔形狀。",
        
        // Tai Mo Shan
        "trail.c5d6e7f8-a9b0-1234-8901-567890123456.name": "大帽山",
        "trail.c5d6e7f8-a9b0-1234-8901-567890123456.summary": "香港最高峰，海拔957米，可通過多條路線到達。",
        
        // The Peak Circle Walk
        "trail.d6e7f8a9-b0c1-2345-9012-678901234567.name": "山頂環迴步行徑",
        "trail.d6e7f8a9-b0c1-2345-9012-678901234567.summary": "圍繞山頂的輕鬆環形步道，可欣賞城市和海港的壯麗景色。",
        
        // Tai Tam Reservoir
        "trail.e7f8a9b0-c1d2-3456-0123-789012345678.name": "大潭水塘",
        "trail.e7f8a9b0-c1d2-3456-0123-789012345678.summary": "圍繞大潭水塘的風景步道，有歷史悠久的堤壩建築。",
        
        // Planner
        "planner.title": "計劃",
        "planner.choose.trail": "選擇路線",
        "planner.schedule": "時間表",
        "planner.date": "日期",
        "planner.note": "備註（集合點、裝備...）",
        "planner.preview": "預覽",
        "planner.select.trail": "選擇路線以查看摘要",
        "planner.saved": "計劃已儲存",
        "planner.saved.message": "您的行山計劃已添加到您的計劃中。",
        
        // Safety
        "safety.progress": "進度",
        "safety.all.complete": "太好了！您已準備好安全行山。",
        "safety.complete.all": "出發前請完成所有項目。",
        "safety.checklist.title": "安全檢查清單",
        "safety.create.items": "創建檢查清單項目",
        "safety.loading": "載入檢查清單中...",
        "safety.add.item": "添加項目",
        "safety.item.title": "項目標題",
        "safety.item.title.placeholder": "輸入項目標題",
        "safety.item.title.required": "項目標題為必填項",
        "safety.item.icon": "圖標",
        "safety.item.save.error": "保存項目失敗",
        "safety.item.location": "啟用實時位置",
        "safety.item.water": "準備 2 公升水",
        "safety.item.heat": "檢查酷熱天氣警告",
        "safety.item.offline": "下載離線地圖",
        "safety.item.share": "與朋友分享行山計劃",
        
        // Trail Alerts
        "alerts.no.active": "尚無活躍警示",
        "alerts.all.clear": "所有路線暢通。享受您的行山之旅！",
        "alerts.critical": "緊急",
        "alerts.active": "活躍警示",
        "alert.category.weather": "天氣",
        "alert.category.maintenance": "維護",
        "alert.category.safety": "安全",
        "alert.category.closure": "封閉",
        "alert.severity.low": "低",
        "alert.severity.medium": "中",
        "alert.severity.high": "高",
        "alert.severity.critical": "嚴重",
        "alert.time.minutes.ago": "分鐘前",
        "alert.time.hours.ago": "小時前",
        "alert.time.days.ago": "天前",
        "alert.issued.at": "發佈",
        "alert.updated.at": "更新",
        "alert.title.route.maintenance": "路線維護",
        "alert.title.weather": "天氣警示",
        "alert.title.safety": "安全警示",
        "alert.title.closure": "路線封閉",
        "alert.detail.maclehose.section2.maintenance": "麥理浩徑第二段近浪茄因斜坡工程部分封閉。有替代路線可供使用。",
        "alert.history.title": "警告歷史",
        "alert.history.empty": "沒有警告歷史",
        "alert.history.description": "查看過去的天氣警告和警示",
        "alert.history.filter.all": "全部",
        "alert.history.filter.active": "活躍",
        "alert.history.filter.cancelled": "已取消",
        "alert.cancelled": "已取消",
        
        // Hike Plan
        "hike.plan.title": "行山計劃",
        "hike.plan.status": "狀態",
        "hike.plan.mark.completed": "標記為已完成",
        "hike.plan.completed.on": "完成日期",
        "hike.plan.update": "更新計劃",
        "hike.plan.delete": "刪除計劃",
        "hike.plan.delete.message": "此行山將從您的計劃中移除。",
        
        // Hike Tracking
        "tracking.title": "行山追蹤",
        "tracking.time": "時間",
        "tracking.distance": "距離",
        "tracking.speed": "速度",
        "tracking.altitude": "海拔",
        "tracking.track.points": "軌跡點",
        "tracking.select.trail": "選擇路線",
        "hike.tracking.select.trail": "選擇路線",
        
        // Hike Records
        "records.title": "行山記錄",
        "records.no.records": "尚無行山記錄",
        "records.start.tracking": "開始追蹤您的行山活動以創建記錄",
        "records.detail": "行山記錄",
        "records.route.track": "路線軌跡",
        "records.no.track.data": "無軌跡數據",
        "records.detailed.stats": "詳細統計",
        "records.max.speed": "最高速度",
        "records.max.altitude": "最高海拔",
        "records.min.altitude": "最低海拔",
        "records.elev.loss": "海拔下降",
        "records.track.points": "軌跡點數",
        "records.elevation.profile": "海拔變化",
        "records.insufficient.data": "數據不足",
        "records.3d.playback": "3D 軌跡回放",
        "records.delete": "刪除記錄",
        "records.delete.confirm": "確定要刪除此行山記錄嗎？此操作無法撤銷。",
        "records.distance": "距離",
        "records.duration": "時長",
        "records.avg.speed": "平均速度",
        "records.elev.gain": "海拔上升",
        "records.start": "起點",
        "records.end": "終點",
        "records.unit.km": "公里",
        "records.unit.kmh": "公里/小時",
        "records.unit.m": "米",
        
        // Location Sharing
        "location.sharing.title": "位置分享",
        "location.sharing.sharing": "正在分享位置",
        "location.sharing.not.sharing": "未分享位置",
        "location.sharing.description": "您的實時位置正在分享給緊急聯繫人",
        "location.sharing.start.description": "點擊下方按鈕開始分享位置",
        "location.sharing.start": "開始分享",
        "location.sharing.stop": "停止分享",
        "location.sharing.sos": "緊急求救",
        "location.sharing.anomaly": "異常檢測",
        "location.sharing.detected.at": "檢測時間",
        "location.sharing.current.location": "當前位置",
        "location.sharing.latitude": "緯度",
        "location.sharing.longitude": "經度",
        "location.sharing.altitude": "海拔",
        "location.sharing.share.link": "分享鏈接",
        "location.sharing.copy.link": "複製鏈接",
        "location.sharing.contacts": "緊急聯繫人",
        "location.sharing.no.contacts": "尚未添加緊急聯繫人",
        "location.sharing.add.contact.description": "請添加至少一個緊急聯繫人以使用位置分享和緊急求救功能",
        "location.sharing.add.contact": "添加緊急聯繫人",
        "location.sharing.contact.info": "聯繫人信息",
        "location.sharing.name": "姓名",
        "location.sharing.phone": "電話號碼",
        "location.sharing.email": "電子郵件（可選）",
        "location.sharing.primary": "主要",
        "location.sharing.sos.confirm": "確認發送緊急求救",
        "location.sharing.sos.message": "這將向所有緊急聯繫人發送您的位置和求救信息。請確認這是緊急情況。",
        "location.sharing.send": "發送",
        
        // Species Identification
        "species.title": "物種識別",
        "species.identifying": "正在識別...",
        "species.take.photo": "拍照",
        "species.photo.library": "相冊",
        "species.habitat": "棲息地",
        "species.distribution": "分佈",
        "species.other.possibilities": "其他可能",
        "species.unable.to.identify": "無法識別",
        "species.history": "識別歷史",
        "species.no.history": "尚無識別記錄",
        "species.start.identifying": "開始識別物種以查看歷史記錄",
        
        // Recommendations
        "recommendations.title": "智能推薦",
        "recommendations.settings": "推薦設置",
        "recommendations.available.time": "可用時間",
        "recommendations.hours": "小時",
        "recommendations.half.hour": "30分鐘",
        "recommendations.hour.and.half": "小時30分鐘",
        "recommendations.regenerate": "重新生成推薦",
        "recommendations.no.recommendations": "暫無推薦",
        "recommendations.adjust.preferences": "請調整您的偏好設置或可用時間",
        "recommendations.for.you": "為您推薦",
        "recommendations.match": "匹配度",
        "recommendations.view.details": "查看詳情",
        "recommendations.preferences": "偏好設置",
        "recommendations.preferred.difficulty": "偏好難度",
        "recommendations.difficulty": "難度",
        "recommendations.no.preference": "無偏好",
        "recommendations.preferred.distance": "偏好距離",
        "recommendations.min": "最小",
        "recommendations.max": "最大",
        
        // Journal
        "journal.title": "日記",
        "journal.create": "創建日記",
        "journal.edit": "編輯日記",
        "journal.detail": "日記詳情",
        "journal.new.entry": "新日記條目",
        "journal.basic.information": "基本資訊",
        "journal.title.field": "標題",
        "journal.hike.date": "行山日期",
        "journal.trail": "路線",
        "journal.location": "位置",
        "journal.select.trail": "選擇路線",
        "journal.change": "更改",
        "journal.content": "內容",
        "journal.photos": "照片",
        "journal.add.photos": "添加照片",
        "journal.delete.confirm": "刪除日記條目",
        "journal.delete.message": "您確定要刪除此日記條目嗎？此操作無法撤銷。",
        "journal.share.date": "日期",
        "journal.share.trail": "路線",
        "journal.share.weather": "天氣",
        "journal.share.shared.from": "來自 Hiking HK",
        
        // Achievements
        "achievements.title": "成就與徽章",
        "achievements.unlocked": "已解鎖",
        "achievements.total": "總數",
        "achievements.new.unlocked": "新成就解鎖！",
        "achievements.congratulations": "恭喜！您解鎖了",
        "achievements.achievement": "成就！",
        "achievements.unlocked.on": "解鎖時間",
        "achievements.filter.all": "全部",
        
        // Gear Checklist
        "gear.title": "智能裝備清單",
        "gear.view.checklist": "查看裝備清單",
        "gear.progress": "進度",
        "gear.required": "必需",
        "gear.required.items": "必需項目",
        "gear.all.required.complete": "所有必需項目已完成！",
        "gear.no.items": "尚無裝備項目",
        "gear.generate.description": "將根據路線難度、天氣和季節生成裝備清單",
        "gear.category.essential": "必需品",
        "gear.category.clothing": "服裝",
        "gear.category.navigation": "導航",
        "gear.category.safety": "安全",
        "gear.category.food": "食物",
        "gear.category.tools": "工具",
        "gear.category.optional": "可選",
        
        // Gear Item Names
        "gear.item.water.bottle": "水壺（最少2升）",
        "gear.item.extra.water": "額外飲用水（每增加2小時加1升）",
        "gear.item.mobile.phone": "手機（充滿電）",
        "gear.item.power.bank": "充電寶",
        "gear.item.id.card": "身份證 / 身份證明文件",
        "gear.item.moisture.tshirt": "速乾T恤",
        "gear.item.hiking.pants": "行山褲 / 短褲",
        "gear.item.hiking.shoes": "行山鞋 / 行山靴",
        "gear.item.socks": "襪子（額外一對）",
        "gear.item.warm.jacket": "保暖外套 / 抓絨衣",
        "gear.item.beanie": "毛帽 / 保暖帽",
        "gear.item.sun.hat": "太陽帽 / 鴨舌帽",
        "gear.item.sunglasses": "太陽眼鏡",
        "gear.item.rain.jacket": "雨衣 / 雨披",
        "gear.item.uv.protection": "防紫外線衣物",
        "gear.item.offline.map": "離線地圖（已下載）",
        "gear.item.compass": "指南針",
        "gear.item.gps.device": "GPS設備（可選備用）",
        "gear.item.first.aid": "急救包",
        "gear.item.whistle": "哨子",
        "gear.item.emergency.blanket": "緊急毯",
        "gear.item.headlamp": "頭燈 / 手電筒",
        "gear.item.sunscreen": "防曬霜（SPF 50+）",
        "gear.item.insect.repellent": "驅蟲劑",
        "gear.item.energy.snacks": "能量零食",
        "gear.item.light.meal": "輕食 / 三明治",
        "gear.item.full.meal": "正餐",
        "gear.item.electrolyte.drink": "電解質飲料 / 運動飲料",
        "gear.item.electrolyte.tablets": "電解質片",
        "gear.item.multi.tool": "多功能工具 / 小刀",
        "gear.item.trekking.poles": "行山杖",
        "gear.item.camera": "相機",
        "gear.item.binoculars": "望遠鏡",
        "gear.item.lightweight.gloves": "輕便手套",
        
        // Offline Maps
        "offline.maps.no.regions": "暫無可用區域",
        "offline.maps.available.regions": "可用區域",
        "offline.maps.create.regions": "創建地圖區域",
        "offline.maps.loading": "載入區域中...",
        "offline.maps.total.downloaded": "總下載量",
        "offline.maps.clear.all": "清除所有下載",
        "offline.maps.downloading": "下載中...",
        "offline.maps.download.error": "下載錯誤",
        "offline.maps.region.hong.kong.island": "香港島",
        "offline.maps.region.kowloon.ridge": "九龍山脊",
        "offline.maps.region.sai.kung.east": "西貢東",
        "offline.maps.region.lantau.north": "大嶼山北",
        "offline.maps.status.not.downloaded": "未下載",
        "offline.maps.status.downloading": "下載中",
        "offline.maps.status.downloaded": "已下載",
        "offline.maps.status.failed": "失敗",
        "offline.maps.status.updating": "更新中",
        "offline.maps.delete.confirm": "刪除離線地圖",
        "offline.maps.delete.message": "您確定要刪除此離線地圖嗎？此操作無法撤銷。",
        
        // AR Identify
        "ar.scanning.skyline": "正在掃描天際線…",
        "ar.found": "找到",
        "ar.point.camera": "將相機對準山脊以識別山峰",
        "ar.searching.landmarks": "正在搜索地標...",
        "ar.recent.identifications": "最近識別",
        "ar.no.landmarks": "尚未識別地標",
        "ar.start.scanning": "開始掃描以識別附近的山峰",
        "ar.start.scan": "開始掃描",
        "ar.stop.scan": "停止掃描",
        
        // Location Sharing (additional)
        "location.share.confirm.sos": "確認發送緊急求救",
        "location.share.sos.message": "這將向所有緊急聯繫人發送您的位置和求救信息。請確認這是緊急情況。",
        "location.share.sharing": "正在分享位置",
        "location.share.not.sharing": "未分享位置",
        "location.share.start": "開始分享",
        "location.share.stop": "停止分享",
        "location.share.send": "發送",
        "location.share.sharing.description": "您的實時位置正在與緊急聯繫人分享",
        "location.share.start.description": "點擊下方按鈕開始分享位置",
        "location.share.anomaly.detection": "異常檢測",
        "location.share.detected.at": "檢測時間",
        "location.share.current.location": "當前位置",
        "location.share.latitude": "緯度",
        "location.share.longitude": "經度",
        "location.share.altitude": "海拔",
        "location.share.share.link": "分享鏈接",
        "location.share.copy.link": "複製鏈接",
        "location.share.emergency.sos": "緊急求救",
        "location.share.emergency.contacts": "緊急聯繫人",
        "location.share.no.emergency.contacts": "尚未添加緊急聯繫人",
        "location.share.add.contact.description": "請添加至少一個緊急聯繫人以使用位置分享和緊急求救功能",
        "location.share.add.emergency.contact": "添加緊急聯繫人",
        "location.share.contact.information": "聯繫人信息",
        "location.share.contact.name": "姓名",
        "location.share.contact.phone": "電話號碼",
        "location.share.contact.email": "電子郵件（可選）",
        "location.share.primary": "主要",
        "location.share.simulator.warning.title": "檢測到模擬器位置",
        "location.share.simulator.warning.message": "當前位置似乎是 iOS 模擬器的默認位置（舊金山）。請在模擬器中設置自定義位置：功能 > 位置 > 自定義位置，或在真實設備上測試。",
        "error": "錯誤",
        
        // Hike Records (additional)
        "hike.records.none": "尚無行山記錄",
        "hike.records.start.tracking": "開始追蹤您的行山活動以創建記錄",
        "hike.records.unnamed.trail": "未命名路線",
        "hike.records.feature.list": "行山記錄列表",
        "hike.records.feature.list.desc": "查看所有已保存的行山記錄",
        "hike.records.feature.detail": "記錄詳情",
        "hike.records.feature.detail.desc": "查看詳細統計、地圖和海拔圖表",
        "hike.records.feature.playback": "3D 軌跡回放",
        "hike.records.feature.playback.desc": "以 3D 地圖回放您的行山軌跡",
        
        // Hike Tracking (additional)
        "hike.tracking.title": "行山追蹤",
        "hike.tracking.time": "時間",
        "hike.tracking.distance": "距離",
        "hike.tracking.speed": "速度",
        "hike.tracking.altitude": "海拔",
        "hike.tracking.track.points": "軌跡點",
        "hike.tracking.current.location": "當前位置",
        "hike.tracking.start": "開始追蹤",
        
        // Recommendations (additional)
        "recommendations.generating": "正在生成推薦...",
        
        // Preferences
        "preferences.title": "偏好設置",
        "preferences.fitness.level": "體能水平",
        "preferences.scenery": "偏好風景",
        "preferences.difficulty": "偏好難度",
        "preferences.distance": "偏好距離",
        "preferences.min": "最小",
        "preferences.max": "最大",
        "preferences.no.preference": "無偏好",
        "preferences.fitness.level.初學者": "初學者",
        "preferences.fitness.level.中級": "中級",
        "preferences.fitness.level.高級": "高級",
        "preferences.fitness.level.專家": "專家",
        "preferences.scenery.海景": "海景",
        "preferences.scenery.山景": "山景",
        "preferences.scenery.森林": "森林",
        "preferences.scenery.水庫": "水庫",
        "preferences.scenery.城市景觀": "城市景觀",
        "preferences.scenery.日落": "日落",
        "preferences.scenery.日出": "日出",
        
        // Species Identification (additional)
        "species.identification.title": "物種識別",
        "species.identification.identifying": "正在識別...",
        "species.identification.take.photo": "拍照",
        "species.identification.photo.library": "相冊",
        "species.identification.habitat": "棲息地",
        
        // Journal (additional)
        "journal.list.title": "行山日記",
        "journal.no.entries": "尚無日記條目",
        "journal.start.documenting": "開始記錄您的行山冒險！",
        "journal.create.first.entry": "創建第一條日記",
        "journal.save.error": "保存錯誤",
        
        // Anomaly Severity
        "anomaly.severity.low": "低",
        "anomaly.severity.medium": "中",
        "anomaly.severity.high": "高",
        "anomaly.severity.critical": "嚴重",
        
        // MTR Real-time Schedule
        "mtr.real.time.schedule": "港鐵實時列車服務",
        "mtr.direction.up": "上行",
        "mtr.direction.down": "下行",
        "mtr.arriving": "即將到站",
        "mtr.minutes": "分鐘",
        "mtr.error.load.failed": "無法載入列車時間表",
        
        // Transport
        "transport.title": "交通查詢",
        "transport.mtr": "港鐵",
        "transport.bus": "巴士",
        "transport.search": "搜尋",
        "transport.mtr.search.title": "搜尋港鐵站",
        "transport.mtr.search.placeholder": "輸入車站名稱（例如：荃灣）",
        "transport.mtr.quick.stations": "快速選擇：",
        "transport.mtr.no.schedule": "暫無時間表",
        "transport.mtr.station.not.found": "找不到車站。請嘗試：荃灣、筲箕灣、中環、金鐘、東涌、觀塘",
        "transport.bus.search.title": "搜尋巴士路線",
        "transport.bus.search.placeholder": "輸入路線號碼或車站名稱",
        "transport.bus.no.results": "找不到結果",
        "transport.bus.results": "搜尋結果",
        "transport.bus.routes.found": "條路線",
        "transport.bus.showing.first.20": "顯示首 20 個結果",
        "transport.bus.stops": "巴士站",
        "transport.bus.eta": "預計到站時間",
        "transport.bus.real.time.eta": "實時到站",
        "transport.bus.loading.eta": "載入中...",
        "transport.bus.outbound": "往",
        "transport.bus.inbound": "返",
        "transport.bus.error.load.failed": "無法載入巴士資訊",
        
        // Home Quick Actions
        "home.transport": "交通"
    ]
}

